files:
- path: app/CMakeLists.txt
  preprocess: true
- path: app/main.cpp
  preprocess: true
- path: lib/public/projectlib/Example.h
  output-path: lib/public/${project_name}lib/Example.h
  preprocess: true
- path: lib/CMakeLists.txt
  preprocess: true
- path: lib/Example.cpp
  preprocess: true
- script/run-cmake
- script/run-cmake.cmd
- path: test/CMakeLists.txt
  preprocess: true
- path: test/ExampleTest.cpp
  preprocess: true
- path: test/main.cpp
  preprocess: true
- .gitignore
- path: CMakeLists.txt
  preprocess: true
  preprocess: true
- path: README.md
  preprocess: true
- path: ../shared/LICENSE
  output-path: LICENSE
  preprocess: true
commands:
- git init
- git submodule add https://github.com/philsquared/Catch.git external/catch
