description: Simple Python tool with virtual environment
files:
- .gitignore
- path: ../shared/LICENSE
  output-path: LICENSE
  preprocess: true
- path: README.md
  preprocess: true
- path: script/bootstrap.cmd
  preprocess: true
- path: script/project.cmd
  output-path: script/$project_name.cmd
  preprocess: true
- path: script/project.py
  output-path: script/$project_name.py
  preprocess: true
- script/requirements.txt
commands:
- git init
- git config user.name "$author"
- git config user.email "$author_email"
- git add .
